artifacts: root

data_gathering:
  root_dir: artifacts/data_gathering
  source_url: https://www.smartprix.com/laptops
  local_data_file: artifacts/data_gathering/smartprix.html

data_ingestion:
  root_dir: artifacts/data_ingestion
  html_file_path: artifacts/data_gathering/smartprix.html
  data_path: artifacts/data_ingestion/smartprix.csv

data_preprocessing:
  root_dir: artifacts/data_preprocessing
  raw_data_path: artifacts/data_ingestion/smartprix.csv
  preprocessed_data_path: artifacts/data_preprocessing/preprocessed_data.csv

data_cleaning:
  root_dir: artifacts/data_cleaning
  preprocessed_data_path: artifacts/data_preprocessing/preprocessed_data.csv
  cleaned_data_path: artifacts/data_cleaning/cleaned_data.csv

missing_value_imputation:
  root_dir: artifacts/missing_value_imputation
  after_cleaning: artifacts/data_cleaning/cleaned_data.csv
  filled_data_path: artifacts/missing_value_imputation/after_missing_value_imputation.csv

feature_selection:
  root_dir: artifacts/feature_selection
  after_missing_value_imputation: artifacts/missing_value_imputation/after_missing_value_imputation.csv
  selected_data_path: artifacts/feature_selection/after_feature_selection.csv
  
  



